---
title: Promise 与异步编程
date: 2020-05-08 07:03:00
tags:
categories:
- JavaScript
---

## 异步编程的背景知识
JavaScript 引擎是基于单线程(single-threaded)事件循环的概念创建的，同一时刻只允许一个代码块在执行，所以需要跟踪即将运行的代码，那些代码被放在一个任务队列(job queue)中，每当一段代码准备执行时，都会被添加到任务队列。


每当 JavaScript 引擎中的一段代码结束执行，事件循环(event loop)会执行队列中的下一个任务，事件循环是 JavaScript 引擎的一个内部处理线程，负责监控代码执行并管理任务队列。

队列中的任务会从第一个一直执行到最后一个。

### 事件模型
向任务队列添加一个新任务来响应用户的操作，只有当前面的任务都完成后它才会被执行。

### 回调模式
Node.js 通过普及回调函数来改进异步编程，回调模式与事件模型类似，异步代码都会在未来的某个时间点执行，二者的区别是：回调模式中被调用的函数是作为参数传入的。
```javascript
readFile('example.txt', function(err, contents) {
    if (err) {
        throw err
    }
    console.log(contents)
})
```
<font color="red">Node.js 传统的错误优先(error-first)回调风格</font>。

但是当嵌套过多的回调函数时就陷入了回调地狱(callback hell)。


## Promise 基础
Promise 是为异步操作的结果所准备的占位符，它不会去订阅一个事件，也不会传递一个回调函数给目标函数，而是让函数返回一个 Promise：
```javascript
// readFile 承诺将在未来的某个时刻完成
let promise = readFile('example.txt')
```
readFile() 不会立即开始读取文件，函数会先返回一个表示异步读取操作的 Promise 对象，未来对这个对象的操作完全取决于 Promise 的生命周期。

### Promise 的生命周期
每个 Promise 都会经历一个短暂的生命周期：先是处于进行中(pending)的状态，此时操作尚未完成，所以它也是未处理(unsettled)的；一旦异步操作执行结束，Promise 则变为已处理(settled)的状态。操作结束后，Promise 可能会进入到以下两种状态中的一个：
- fulfilled, Promise 异步操作成功完成
- rejected, 由于程序错误或其他一些原因，Promise 异步操作未能成功完成

内部属性 `[[PromiseStatus]]` 被用来表示 Promise 的 3 中状态：'pending'、'fulfilled' 及 'rejected'，这个属性不暴露在 Promise 对象上，所以不能以编程的方式检查 Promise 的状态，只有当 Promise 的状态改变时，通过 then() 方法来采取特定的行动。

内部属性 `[[PromiseValue]]` 用来表示 Promise 处理的结果。

所有 Promise 都有 then() 方法，它接受两个参数：第一个是当 Promise 的状态变为 fulfilled 时需调用的函数，与异步操作相关的附加数据都会传递给这个完成函数(fulfillment handler)；第二个是当 Promise 的状态变为 rejected 时要调用的函数，所有与失败状态相关的附加数据都会传递给这个拒绝函数(rejection handler)。

注意⚠️：如果一个对象实现了上述的 then() 方法，那这个对象称之为 Thenable 对象。所有的 Promise 都是 Thenable 对象，但并非所有 Thenable 对象都是 Promise。

then() 的两个参数都是可选的，所以可以按照任意组合的方式来监听 Promise。

Promise 还有一个 catch() 方法，相当于只给其传入拒绝处理程序的 then() 方法。

then() 方法和 catch() 方法组合使用来正确处理异步操作的结果。此体系要优于事件和回调函数，因为它让操作是成功还是失败变得完全清晰(事件模式倾向于在出错时不被触发，而在回调函数模式中必须始终检查错误参数)。如果未给 Promise 添加拒绝处理函数，所有的错误就会静默发生。

建议：始终附加一个拒绝处理函数，即使该处理程序只是用于打印错误日志。

如果一个 Promise 处于已处理状态，在这之后添加到任务队列中的处理程序仍将执行。这允许你随时添加新的完成或拒绝处理程序，同时也可以保证这些处理程序能被调用。
```javascript
let promise = readFile('example.txt')

// 最初的完成处理程序
promise.then(function(contents) {
    console.log(contents)

    // 现在又添加一个
    promise.then(function(contents) {
        console.log(contents)
    })
})
```

每次调用 then() 方法或 catch() 方法都会创建一个新任务，它会在 Promise 已决议时被执行，这些任务最终会被加入到一个为 Promise 保留的独立队列中。

### 创建未完成的 Promise
新的 Promise 使用 Promise 构造器来创建，此构造器接受单个参数：一个被称为执行器(executor)的函数，包含初始化 Promise 的代码。

该执行器接受两个参数，分别是 resolve() 函数和 reject() 函数，执行器成功完成时调用 resolve() 函数，反之，失败时调用 reject() 函数。
```javascript
let fs = require('fs')

function readFile(filename) {
    return new Promise(function(resolve, reject) {
        // 触发异步操作
        fs.readFile(filename, { encoding: 'utf8' }, function(err, contents) {

            // 检查是否有错误
            if (err) {
                reject(err);
                return;
            }

            // 成功读取文件
            resolve(contents);
        });
    });
}
```
注意：readFile() 方法被调用时执行器会立刻执行，在执行器中，无论是调用 resolve() 还是 reject()，都会向任务队列中添加一个任务来决议这个 Promise，这被称为任务调度(job scheduling)。

在任务调度时，会向任务队列中添加一个新任务，并明确指定将任务延后执行。例如，setTimeout() 函数能够指定一个延迟时间，延迟之后任务才会被添加到队列。

Promise 的执行器会立即执行，早于源代码中在其之后的任何代码。
```javascript
let promise = new Promise(function(resolve, reject) {
    console.log('Promise');
    resolve();
})
console.log('Hi');

// Promise
// Hi
```
调用 resolve() 触发了一个异步操作。传递给 then() 和 catch() 方法的函数会被添加到任务队列中并异步执行。
```javascript
let promise = new Promise(function(resolve, reject) {
    console.log('Promise');
    resolve();
})

promise.then(function() {
    console.log('Resolved');
})
console.log('Hi');

// Promise
// Hi
// Resolved
```
注意：完成处理函数与拒绝处理函数总是在执行器完成后才被添加到任务队列的末尾。

### 创建已处理的 Promise
基于 Promise 执行器行为的动态本质，Promise 构造器就是创建未处理的 Promise 的最好方法。

但如果想用 Promise 来表示一个已知值，那么安排一个单纯传值给 resolve() 函数的任务并没有意义，相反，有两种方法可使用指定值来创建已处理的 Promise。

#### 使用 Promise.resolve()
Promise.resolve() 方法接受一个参数并返回一个完成态的 Promise，这意味着没有任何任务调度会发生，而且需要向 Promise 添加一至多个完成处理函数来提取这个参数。
```javascript
let promise = Promise.resolve(42);

promise.then(function(value) {
    console.log(value);
})

console.log('Hi!')

// Hi
// 42
```
若一个拒绝处理函数被添加到此 Promise，该拒绝处理函数将永不会被调用，因为该 Promise 永远不会存在拒绝状态。

#### 使用 Promise.reject()
Promise.reject() 方法创建一个已拒绝的 Promise。
```javascript
let promise = Promise.reject(42)

promise.catch(function(value) {
    console.log(value);
})
```

若传递一个 Promise 给 Promise.resolve() 或 Promise.reject() 方法：
- 若传入的 Promise 为挂起态，则 Promise.resolve () 调用该 Promise 会不作修改原样返回。此后，若决议原 Promise，在 then() 中可以接收到原例中的参数；而若拒绝原 Promise，则在 catch() 中可以接收到参数 42。但 Promise.reject() 调用则会对原先的 Promise 重新进行包装，对其使用 catch() 可以捕捉到错误，处理函数中的值就是原先处于挂起状态的 Promise。

```javascript
// -1.1
var p = new Promise(function(resolve, reject){});
var p1 = Promise.resolve(p);
console.log(p1 === p) // true
// -1.2
var p = new Promise(function(resolve, reject){
    setTimeout(function() {
        resolve(42);
    }, 500);
});
var p1 = Promise.resolve(p);
p1.then(function(res){ 
    console.log(res) // 42
})
// -1.3
var p = new Promise(function(resolve, reject){
    setTimeout(function() {
        reject(42);
    }, 500);
});
var p1 = Promise.resolve(p);
p1.catch(function(res){ 
    console.log(res) // 42
})

// -1.4
var p = new Promise(function(resolve, reject){});
var p1 = Promise.reject(p);
console.log(p1 === p) // false
p1.catch(function(err) {
    console.log(err === p) // true
})
```
- 若传入的 Promise 为完成态，则 Promise.resolve() 调用该 Promise 原样返回，在 then() 中可以接收到原例中的参数 42。但 Promise.reject() 调用则会对原先的 Promise 重新进行包装，对其使用 catch() 可以捕捉到错误，处理函数中的值就是原先处于完成状态的 Promise。
```javascript
// -2.1
var p = Promise.resolve(42)
var p1 = Promise.resolve(p);
console.log(p === p1)

// -2.2
var p = Promise.resolve(42);
var p1 = Promise.reject(p);
console.log(p1 === p) // false
p1.catch(function(err) {
    console.log(err === p) // true
})
```
- 若传入的 Promise 为拒绝态，则 Promise.resolve() 调用该 Promise 原样返回，对其使用 catch() 完成处理，then() 并不执行。但 Promise.reject() 调用则会对原先的 Promise 重新进行包装，对其使用 catch() 可以捕捉到错误，处理函数中的值就是原先处于拒绝状态的 Promise。
```javascript
// -3.1
var p = Promise.reject(42)
var p1 = Promise.resolve(p);
console.log(p === p1)
p1.then(function(res) {
    console.log('done'); // 不会执行
}).catch(function(err) {
    console.log(err) // 42
})
// -3.2
var p = Promise.reject(42)
var p1 = Promise.reject(p);
console.log(p === p1) // false
p1.catch(function(err) {
    console.log(err === p) // true
})
```
总结：向 Promise.resolve() 方法传入一个 Promise，那么这个 Promise 会被直接返回；向 Promise.reject() 方法传入一个 Promise，那么都会在原 Promise 上包装出一个新的 Promise 后返回。


#### 非 Promise 的 Thenable 对象
Promise.resolve() 与 Promise.reject() 都可以接受非 Promise 的 Thenable 对象作为参数。如果传入了一个非 Promise 的 Thenable 对象，则这些方法会创建一个新的 Promise，并在 then() 函数中被调用。

当一个对象拥有一个能接受 resolve 与 reject 参数的 then() 方法，该对象就会被认为是一个非 Promise 的 Thenable 对象：
```javascript
let thenable = {
    then:  function(resolve, reject) {
        resolve(42);
    }
}

// 可以调用 Promise.resolve 来将一个 Thenable 对象转换为已完成的 Promise
let p1  = Promise.resolve(thenable)
p1.then(function(res) {
    console.log(res); // 42
})
```
Promise.resolve() 调用了 thenable.then()，确定这个 Thenable 对象的状态。

使用 Promise.resolve()，同样还能从一个 Thenable 对象创建一个已拒绝的 Promise：
```javascript
let thenable = {
    then:  function(resolve, reject) {
        reject(42);
    }
}

// 可以调用 Promise.resolve 来将一个 Thenable 对象转换为已完成的 Promise
let p1  = Promise.resolve(thenable)
p1.catch(function(res) {
    console.log(res); // 42
})
```
有了 Promise.resolve() 与 Promise.reject() 方法，可以轻松地处理非 Promise 的 Thenable 对象。

当不能确定某个对象是否是 Promise 时，将该对象传递给 Promise.resolve() 或 Promise.reject() (取决于你的预期结果)是能找出的最好方式，因为传入真正的 Promise 只会被直接传递出来，并不会被修改。

### 执行器错误
如果执行器内部抛出一个错误，则 Promise 的拒绝处理程序就会被调用：
```javascript
let promise = new Promise(function(resolve, reject) {
    throw new Error("Explosion");
})

promise.catch(function(err) {
    console.log(err.message) // Explosion
})
```

explosion \[ɪkˈsploʊʒn] n.爆炸，爆破，爆裂(声); 突增; 猛增; 激增; (感情，尤指愤怒的) 突然爆发，迸发;

每个执行器中都隐含一个 try-catch 块，所以错误会被捕获并传入拒绝处理函数，相当于：
```javascript
let promise = new Promise(function(resolve, reject) {
    try {
        throw new Error("Explosion");
    } catch (ex) {
        reject(ex);
    }
    
})

promise.catch(function(err) {
    console.log(err.message) // Explosion
})
```

执行器处理程序捕获了抛出的任何错误，以简化这种常见处理，但在执行器内抛出的错误仅当存在拒绝处理函数时才会被报告，否则这个错误就会被隐藏。

为避免上述问题，JavaScript 环境通过提供钩子(hook)来捕获被拒绝的 Promise。


## 全局的 Promise 拒绝处理
Promise 最有争议的方面之一就是：当一个 Promise 被拒绝时若缺少拒绝处理函数，就会静默失败。

Promise 的特性决定了很难检测一个 Promise 是否被处理过：
```javascript
let rejected = Promise.reject(42);

// 此时, rejected 还没有被处理

// 一段时间后
rejected.catch(function(value) {
    // 现在 rejected 已经被处理了
    console.log(value)
})
```
任何时候都可以调用 then() 或 catch() 方法，无论 Promise 是否已被解决，这两个方法都可以正常工作，这导致很难准确知道一个 Promise 何时会被处理。

### Node.js 的拒绝处理
在 Node.js 中，处理 Promise 拒绝时会触发 `process` 对象上的两个事件：
- `unhandledRejection`：在一个事件循环中，当 Promise 被拒绝，并且没有提供拒绝处理函数时，触发该事件。
- `rejectionHandled`：在一个事件循环后，当 Promise 被拒绝时，若拒绝处理函数被调用，触发该事件。

这两个事件旨在帮助识别已被拒绝但未曾被处理过的 Promise。

`unhandledRejection` 事件处理函数接受的参数是拒绝原因(通常是一个错误对象)以及已被拒绝的 Promise，`rejectedHandled` 事件处理函数则只有一个参数，即已被拒绝的 Promise：
```javascript
let rejected;

process.on("unhandledRejection", function(reason, promise) {
    console.log("unhandled rejection")
    console.log(reason.message);
    console.log(rejected === promise)
})

process.on("rejectionHandled", function(promise) {
    console.log('rejection handled');
    console.log(rejected === promise)
})

rejected = Promise.reject(new Error("Explosion"));

// 延时添加拒绝处理程序
setTimeout(function() {
    rejected.catch(function(err){
        console.log(err.message);
    });
}, 1000);

/**
 执行结果：
 1.unhandled rejection
   Explosion
   true
 2.Explosion
 3.rejection handled
   true
 */
```
这里的 `rejectionHandled` 事件在拒绝处理函数最终被调用时触发。

如果在创建 rejected 之后直接添加拒绝处理程序，那么 `rejectionHandled` 事件不会被触发，因为 rejected 创建的过程与拒绝处理程序的调用在同一个事件循环中，此时 `rejectionHandled` 事件尚未生效。

通过事件 `rejectionHandled` 和事件 `unhandledRejection` 将潜在未处理的拒绝存储为一个列表，等待一段时间后检查此列表，便能够正确地跟踪潜在的未处理拒绝。

### 浏览器的拒绝处理
浏览器也是通过触发两个事件来识别未处理的拒绝的，这两个事件会被 window 对象触发，并完全等效于 Node.js 的相关事件。

- `unhandledrejection`：在一个事件循环中，当 Promise 被拒绝，并且没有提供拒绝处理函数时，触发该事件。
- `rejectionhandled`：在一个事件循环后，当 Promise 被拒绝时，若拒绝处理函数被调用，触发该事件。

在 Node.js 实现中，事件处理程序接收多个独立参数，而浏览器事件的处理函数接受一个有以下属性的事件对象作为参数：
- type，事件的名称，`unhandledrejection` 或 `rejectionhandled`
- promise，被拒绝的 Promise 对象
- reaseon，Promise 中的拒绝值(拒绝原因)

浏览器实现中另一处不同是：在两个事件中都可以使用拒绝值。

```javascript
window.addEventListener('unhandledrejection', event =>
{
    console.log(event.reason);
});
 
window.addEventListener('rejectionhandled', event =>
{
    console.log('rejection handled');
});
 
function foo()
{
    return Promise.reject('Hello, Fundebug!');
}
 
var r = foo();
 
setTimeout(() =>
{
    r.catch(e =>{});
}, 1000);

// 注意：Version 81.0.4044.138 (Official Build) (64-bit) 浏览器中未按照如上预期打印
// 首先是报 error 的红色如下信息，然后 1s 后变成正常的 info 灰色
// Uncaught (in promise) Hello, Fundebug!
```


## 串联 Promise
每次调用 then() 方法或 catch() 方法实际上创建并返回了另一个 Promise，只有当第一个 Promise 完成或被拒绝后，第二个才会解决。

### 捕获错误
完成处理程序或拒绝处理程序中可能发生错误，而 Promise 链可以用来捕获这些错误。

务必在 Promise 链的末尾留有一个拒绝处理程序以确保能够正确处理所有可能发生的错误。

### Promise 链的返回值
Promise 链的一个重要特性是可以给下游 Promise 传递数据。

### 在 Promise 链中返回 Promise


## 响应多个 Promise
### Promise.all() 方法
Promise.all() 方法只接受一个参数并返回一个 Promise，该参数是一个含有多个受监视 Promise 的可迭代对象(例如，一个数组)，只有当可迭代对象中的所有 Promise 都被解决后返回的 Promise 才会被解决，只有当可迭代对象中所有 Promise 都被完成后返回的 Promise 才会被完成。

完成处理程序的结果是一个包含每个解决值的数组，这些值按照传入参数数组中 Promise 的顺序存储，所以可以根据每个结果来匹配对应的 Promise。

所有传入 Promise.all() 方法的 Promise 只要有一个被拒绝，那么返回的 Promise 没等所有 Promise 都完成就立即被拒绝。

拒绝处理程序总是接受一个值而非数组，该值来自被拒绝 Promise 的拒绝值。

### Promise.race() 方法
Promise.race() 方法接受含多个受监视 Promise 的可迭代对象作为唯一参数并返回一个 Promise，但只要有一个 Promise 被解决返回的 Promise 就被解决，无须等待所有 Promise 都被完成。

传给 Promise.race() 方法的 Promise 会进行竞选，以决出哪一个先被解决，如果先解决的是已完成 Promise，则返回已完成 Promise；如果先解决的是已拒绝 Promise，则返回已拒绝 Promise。


## 自 Promise 继承
可以定义自己的 Promise 来扩展内置 Promise 功能。
```javascript
class MyPromise extends Promise {

    // 使用默认构造函数

    success(resolve, reject) {
        return this.then(resolve, reject)
    }

    failure(reject) {
        return this.catch(reject)
    }
}
```
MyPromise.resolve() 方法和 MyPromise.reject() 方法通过 Symbol.species 属性来决定返回 Promise 的类型，故调用这两个方法时，无论传入什么值都会返回一个 MyPromise 的实例。


## 基于 Promise 的异步任务执行


## 总结
Promise 编排的任务会被添加到 JavaScript 引擎任务队列并在未来执行，还有一个任务队列用于跟踪 Promise 的完成处理程序和拒绝处理程序并确保正确执行。


## 参考
[1] Zakas, Nicholas C. Understanding ECMAScript 6.